<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('provincias')->insert([
            ['id_departamento' => 1, 'provincia' => 'Chachapoyas'],
            ['id_departamento' => 1, 'provincia' => 'Bagua'],
            ['id_departamento' => 1, 'provincia' => 'Bongará'],
            ['id_departamento' => 1, 'provincia' => 'Condorcanqui'],
            ['id_departamento' => 1, 'provincia' => 'Luya'],
            ['id_departamento' => 1, 'provincia' => 'Rodríguez de Mendoza'],
            ['id_departamento' => 1, 'provincia' => 'Utcubamba'],
            ['id_departamento' => 2, 'provincia' => 'Huaraz'],
            ['id_departamento' => 2, 'provincia' => 'Aija'],
            ['id_departamento' => 2, 'provincia' => 'Antonio Raymondi'],
            ['id_departamento' => 2, 'provincia' => 'Asunción'],
            ['id_departamento' => 2, 'provincia' => 'Bolognesi'],
            ['id_departamento' => 2, 'provincia' => 'Carhuaz'],
            ['id_departamento' => 2, 'provincia' => 'Carlos Fermín Fitzcarrald'],
            ['id_departamento' => 2, 'provincia' => 'Casma'],
            ['id_departamento' => 2, 'provincia' => 'Corongo'],
            ['id_departamento' => 2, 'provincia' => 'Huari'],
            ['id_departamento' => 2, 'provincia' => 'Huarmey'],
            ['id_departamento' => 2, 'provincia' => 'Huaylas'],
            ['id_departamento' => 2, 'provincia' => 'Mariscal Luzuriaga'],
            ['id_departamento' => 2, 'provincia' => 'Ocros'],
            ['id_departamento' => 2, 'provincia' => 'Pallasca'],
            ['id_departamento' => 2, 'provincia' => 'Pomabamba'],
            ['id_departamento' => 2, 'provincia' => 'Recuay'],
            ['id_departamento' => 2, 'provincia' => 'Santa'],
            ['id_departamento' => 2, 'provincia' => 'Sihuas'],
            ['id_departamento' => 2, 'provincia' => 'Yungay'],
            ['id_departamento' => 3, 'provincia' => 'Abancay'],
            ['id_departamento' => 3, 'provincia' => 'Andahuaylas'],
            ['id_departamento' => 3, 'provincia' => 'Antabamba'],
            ['id_departamento' => 3, 'provincia' => 'Aymaraes'],
            ['id_departamento' => 3, 'provincia' => 'Cotabambas'],
            ['id_departamento' => 3, 'provincia' => 'Chincheros'],
            ['id_departamento' => 3, 'provincia' => 'Grau'],
            ['id_departamento' => 4, 'provincia' => 'Arequipa'],
            ['id_departamento' => 4, 'provincia' => 'Camaná'],
            ['id_departamento' => 4, 'provincia' => 'Caravelí'],
            ['id_departamento' => 4, 'provincia' => 'Castilla'],
            ['id_departamento' => 4, 'provincia' => 'Caylloma'],
            ['id_departamento' => 4, 'provincia' => 'Condesuyos'],
            ['id_departamento' => 4, 'provincia' => 'Islay'],
            ['id_departamento' => 4, 'provincia' => 'La Unión'],
            ['id_departamento' => 5, 'provincia' => 'Huamanga'],
            ['id_departamento' => 5, 'provincia' => 'Cangallo'],
            ['id_departamento' => 5, 'provincia' => 'Huanca Sancos'],
            ['id_departamento' => 5, 'provincia' => 'Huanta'],
            ['id_departamento' => 5, 'provincia' => 'La Mar'],
            ['id_departamento' => 5, 'provincia' => 'Lucanas'],
            ['id_departamento' => 5, 'provincia' => 'Parinacochas'],
            ['id_departamento' => 5, 'provincia' => 'Páucar del Sara Sara'],
            ['id_departamento' => 5, 'provincia' => 'Sucre'],
            ['id_departamento' => 5, 'provincia' => 'Víctor Fajardo'],
            ['id_departamento' => 5, 'provincia' => 'Vilcas Huamán'],
            ['id_departamento' => 6, 'provincia' => 'Cajamarca'],
            ['id_departamento' => 6, 'provincia' => 'Cajabamba'],
            ['id_departamento' => 6, 'provincia' => 'Celendín'],
            ['id_departamento' => 6, 'provincia' => 'Chota'],
            ['id_departamento' => 6, 'provincia' => 'Contumazá'],
            ['id_departamento' => 6, 'provincia' => 'Cutervo'],
            ['id_departamento' => 6, 'provincia' => 'Hualgayoc'],
            ['id_departamento' => 6, 'provincia' => 'Jaén'],
            ['id_departamento' => 6, 'provincia' => 'San Ignacio'],
            ['id_departamento' => 6, 'provincia' => 'San Marcos'],
            ['id_departamento' => 6, 'provincia' => 'San Miguel'],
            ['id_departamento' => 6, 'provincia' => 'San Pablo'],
            ['id_departamento' => 6, 'provincia' => 'Santa Cruz'],
            ['id_departamento' => 7, 'provincia' => 'Prov. Const. del Callao'],
            ['id_departamento' => 8, 'provincia' => 'Cusco'],
            ['id_departamento' => 8, 'provincia' => 'Acomayo'],
            ['id_departamento' => 8, 'provincia' => 'Anta'],
            ['id_departamento' => 8, 'provincia' => 'Calca'],
            ['id_departamento' => 8, 'provincia' => 'Canas'],
            ['id_departamento' => 8, 'provincia' => 'Canchis'],
            ['id_departamento' => 8, 'provincia' => 'Chumbivilcas'],
            ['id_departamento' => 8, 'provincia' => 'Espinar'],
            ['id_departamento' => 8, 'provincia' => 'La Convención'],
            ['id_departamento' => 8, 'provincia' => 'Paruro'],
            ['id_departamento' => 8, 'provincia' => 'Paucartambo'],
            ['id_departamento' => 8, 'provincia' => 'Quispicanchi'],
            ['id_departamento' => 8, 'provincia' => 'Urubamba'],
            ['id_departamento' => 9, 'provincia' => 'Huancavelica'],
            ['id_departamento' => 9, 'provincia' => 'Acobamba'],
            ['id_departamento' => 9, 'provincia' => 'Angaraes'],
            ['id_departamento' => 9, 'provincia' => 'Castrovirreyna'],
            ['id_departamento' => 9, 'provincia' => 'Churcampa'],
            ['id_departamento' => 9, 'provincia' => 'Huaytará'],
            ['id_departamento' => 9, 'provincia' => 'Tayacaja'],
            ['id_departamento' => 10, 'provincia' => 'Huánuco'],
            ['id_departamento' => 10, 'provincia' => 'Ambo'],
            ['id_departamento' => 10, 'provincia' => 'Dos de Mayo'],
            ['id_departamento' => 10, 'provincia' => 'Huacaybamba'],
            ['id_departamento' => 10, 'provincia' => 'Huamalíes'],
            ['id_departamento' => 10, 'provincia' => 'Leoncio Prado'],
            ['id_departamento' => 10, 'provincia' => 'Marañón'],
            ['id_departamento' => 10, 'provincia' => 'Pachitea'],
            ['id_departamento' => 10, 'provincia' => 'Puerto Inca'],
            ['id_departamento' => 10, 'provincia' => 'Lauricocha'],
            ['id_departamento' => 10, 'provincia' => 'Yarowilca'],
            ['id_departamento' => 11, 'provincia' => 'Ica'],
            ['id_departamento' => 11, 'provincia' => 'Chincha'],
            ['id_departamento' => 11, 'provincia' => 'Nazca'],
            ['id_departamento' => 11, 'provincia' => 'Palpa'],
            ['id_departamento' => 11, 'provincia' => 'Pisco'],
            ['id_departamento' => 12, 'provincia' => 'Huancayo'],
            ['id_departamento' => 12, 'provincia' => 'Concepción'],
            ['id_departamento' => 12, 'provincia' => 'Chanchamayo'],
            ['id_departamento' => 12, 'provincia' => 'Jauja'],
            ['id_departamento' => 12, 'provincia' => 'Junín'],
            ['id_departamento' => 12, 'provincia' => 'Satipo'],
            ['id_departamento' => 12, 'provincia' => 'Tarma'],
            ['id_departamento' => 12, 'provincia' => 'Yauli'],
            ['id_departamento' => 12, 'provincia' => 'Chupaca'],
            ['id_departamento' => 13, 'provincia' => 'Trujillo'],
            ['id_departamento' => 13, 'provincia' => 'Ascope'],
            ['id_departamento' => 13, 'provincia' => 'Bolívar'],
            ['id_departamento' => 13, 'provincia' => 'Chepén'],
            ['id_departamento' => 13, 'provincia' => 'Julcán'],
            ['id_departamento' => 13, 'provincia' => 'Otuzco'],
            ['id_departamento' => 13, 'provincia' => 'Pacasmayo'],
            ['id_departamento' => 13, 'provincia' => 'Pataz'],
            ['id_departamento' => 13, 'provincia' => 'Sánchez Carrión'],
            ['id_departamento' => 13, 'provincia' => 'Santiago de Chuco'],
            ['id_departamento' => 13, 'provincia' => 'Gran Chimú'],
            ['id_departamento' => 13, 'provincia' => 'Viru'],
            ['id_departamento' => 14, 'provincia' => 'Chiclayo'],
            ['id_departamento' => 14, 'provincia' => 'Ferreñafe'],
            ['id_departamento' => 14, 'provincia' => 'Lambayeque'],
            ['id_departamento' => 15, 'provincia' => 'Lima'],
            ['id_departamento' => 15, 'provincia' => 'Barranca'],
            ['id_departamento' => 15, 'provincia' => 'Cajatambo'],
            ['id_departamento' => 15, 'provincia' => 'Canta'],
            ['id_departamento' => 15, 'provincia' => 'Cañete'],
            ['id_departamento' => 15, 'provincia' => 'Huaral'],
            ['id_departamento' => 15, 'provincia' => 'Huarochirí'],
            ['id_departamento' => 15, 'provincia' => 'Huaura'],
            ['id_departamento' => 15, 'provincia' => 'Oyón'],
            ['id_departamento' => 15, 'provincia' => 'Yauyos'],
            ['id_departamento' => 16, 'provincia' => 'Maynas'],
            ['id_departamento' => 16, 'provincia' => 'Alto Amazonas'],
            ['id_departamento' => 16, 'provincia' => 'Loreto'],
            ['id_departamento' => 16, 'provincia' => 'Mariscal Ramón Castilla'],
            ['id_departamento' => 16, 'provincia' => 'Requena'],
            ['id_departamento' => 16, 'provincia' => 'Ucayali'],
            ['id_departamento' => 16, 'provincia' => 'Datem del Marañón'],
            ['id_departamento' => 16, 'provincia' => 'Putumayo'],
            ['id_departamento' => 17, 'provincia' => 'Tambopata'],
            ['id_departamento' => 17, 'provincia' => 'Manu'],
            ['id_departamento' => 17, 'provincia' => 'Tahuamanu'],
            ['id_departamento' => 18, 'provincia' => 'Mariscal Nieto'],
            ['id_departamento' => 18, 'provincia' => 'General Sánchez Cerro'],
            ['id_departamento' => 18, 'provincia' => 'Ilo'],
            ['id_departamento' => 19, 'provincia' => 'Pasco'],
            ['id_departamento' => 19, 'provincia' => 'Daniel Alcides Carrión'],
            ['id_departamento' => 19, 'provincia' => 'Oxapampa'],
            ['id_departamento' => 20, 'provincia' => 'Piura'],
            ['id_departamento' => 20, 'provincia' => 'Ayabaca'],
            ['id_departamento' => 20, 'provincia' => 'Huancabamba'],
            ['id_departamento' => 20, 'provincia' => 'Morropón'],
            ['id_departamento' => 20, 'provincia' => 'Paita'],
            ['id_departamento' => 20, 'provincia' => 'Sullana'],
            ['id_departamento' => 20, 'provincia' => 'Talara'],
            ['id_departamento' => 20, 'provincia' => 'Sechura'],
            ['id_departamento' => 21, 'provincia' => 'Puno'],
            ['id_departamento' => 21, 'provincia' => 'Azángaro'],
            ['id_departamento' => 21, 'provincia' => 'Carabaya'],
            ['id_departamento' => 21, 'provincia' => 'Chucuito'],
            ['id_departamento' => 21, 'provincia' => 'El Collao'],
            ['id_departamento' => 21, 'provincia' => 'Huancané'],
            ['id_departamento' => 21, 'provincia' => 'Lampa'],
            ['id_departamento' => 21, 'provincia' => 'Melgar'],
            ['id_departamento' => 21, 'provincia' => 'Moho'],
            ['id_departamento' => 21, 'provincia' => 'San Antonio de Putina'],
            ['id_departamento' => 21, 'provincia' => 'San Román'],
            ['id_departamento' => 21, 'provincia' => 'Sandia'],
            ['id_departamento' => 21, 'provincia' => 'Yunguyo'],
            ['id_departamento' => 22, 'provincia' => 'Moyobamba'],
            ['id_departamento' => 22, 'provincia' => 'Bellavista'],
            ['id_departamento' => 22, 'provincia' => 'El Dorado'],
            ['id_departamento' => 22, 'provincia' => 'Huallaga'],
            ['id_departamento' => 22, 'provincia' => 'Lamas'],
            ['id_departamento' => 22, 'provincia' => 'Mariscal Cáceres'],
            ['id_departamento' => 22, 'provincia' => 'Picota'],
            ['id_departamento' => 22, 'provincia' => 'Rioja'],
            ['id_departamento' => 22, 'provincia' => 'San Martín'],
            ['id_departamento' => 22, 'provincia' => 'Tocache'],
            ['id_departamento' => 23, 'provincia' => 'Tacna'],
            ['id_departamento' => 23, 'provincia' => 'Candarave'],
            ['id_departamento' => 23, 'provincia' => 'Jorge Basadre'],
            ['id_departamento' => 23, 'provincia' => 'Tarata'],
            ['id_departamento' => 24, 'provincia' => 'Tumbes'],
            ['id_departamento' => 24, 'provincia' => 'Contralmirante Villar'],
            ['id_departamento' => 24, 'provincia' => 'Zarumilla'],
            ['id_departamento' => 25, 'provincia' => 'Coronel Portillo'],
            ['id_departamento' => 25, 'provincia' => 'Atalaya'],
            ['id_departamento' => 25, 'provincia' => 'Padre Abad'],
            ['id_departamento' => 25, 'provincia' => 'Purus']
        ]);
    }
}
